spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/ssm_db
      username: root
      password: 123456

mybatis-plus:
  global-config:
    db-config:
      # ?? mybatis-plus ??????? id ???
      id-type: auto
  configuration:
    # ?? mybatis-plus ????????
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
